### ISSUE TITLE
Planning Domains repository tests failing

### ISSUE THREAD

**Issue by ReubenJ** [JuliaPlanners/PlanningDomains.jl#4]
The following line throws an `AssertionError`:

https://github.com/JuliaPlanners/PlanningDomains.jl/blob/ccfb33701f33e2be4b5075e7e7a147783bcabadb/test/runtests.jl#L51

when loading the following PDDL file: `1188-m10-strips.pddl`. This occurs because the file is a domain file. This appears to be either a bug with [`list_problems(...)`](https://github.com/JuliaPlanners/PlanningDomains.jl/blob/ccfb33701f33e2be4b5075e7e7a147783bcabadb/src/ipc_instances_repo.jl#L101) or an error in the data returned by the API.

**Comment by ztangent** [comment]
It looks like this may be an API issue (or an issue with a file being mislabeled, see https://github.com/AI-Planning/classical-domains/issues/16) -- will push a workaround to the test suite for now!

**Comment by ztangent** [comment]
Fixed by 0bb5c40d7fde852a170becc4fe8514ca234b0914.
